# Generated by Django 3.2.9 on 2021-12-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20211128_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
    ]
